spring:
  redis:
    database: 1
    host: 127.0.0.1
  application:
    name: x-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
server:
  port: 8080
